server:
  port: 8888

spring:
  datasource:
    url: jdbc:p6spy:mysql://localhost:3306/bulk?profileSQL=true&rewriteBatchedStatements=true
    username: sa
    password: 1234
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: false
        format_sql: false
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 10000

logging:
  level:
    p6spy: info
